extends "res://tests/presentation/verify_card_creation_guided.gd"
func _click(button: Button) -> void:
	var parent := button.get_parent()
	while parent != null:
		if parent is ScrollContainer: parent.ensure_control_visible(button)
		parent = parent.get_parent()
	await _frames()
	await super._click(button)
func _tree_control(ui: Node, key: String, meta: String = "tree_action") -> Control:
	for c in ui.find_children("*", "Control", true, false):
		if c.get_meta(meta, "") == key: return c
	_expect(false, "Missing tree control " + key); return null
func _tree_line(ui: Node, key: String, value: String) -> void:
	var line = _tree_control(ui, key, "tree_field"); line.text = value; line.text_changed.emit(value)
func _canvas_click(ui, id: String, edge: bool = false) -> void:
	await _frames()
	await _click(_tree_control(ui, id, "tree_edge" if edge else "tree_node")); await _frames()
func _key(code: Key, command: bool = false, shift: bool = false) -> void:
	var event := InputEventKey.new(); event.keycode = code; event.pressed = true; event.meta_pressed = command; event.shift_pressed = shift
	root.push_input(event); await process_frame
	event = event.duplicate(); event.pressed = false; root.push_input(event); await _frames()
func _confirm_trade(ui, key: String) -> void:
	await _click(_tree_control(ui, "trade." + key)); await _frames()
	_expect(ui._trade_bar.visible, "trade asks for confirmation: " + key)
	await _click(_tree_control(ui, "trade.confirm")); await _frames()
func _value(ui, key: String) -> String:
	return _tree_control(ui, key + ".value", "tree_field").text
func _run() -> void:
	root.size = Vector2i(1920, 1080)
	var screen = SCREEN.new(); screen.loadout_mode = "progression"; root.add_child(screen); await _frames()
	await _click(screen._admin_button); await _frames()
	await _click(_control(screen, "admin.trees")); await _frames()
	var ui = screen.get_node("CardTreeWorkspace")
	_expect(ui.draft.nodes.is_empty(), "admin opens empty tree when none published")
	var brace_before: Dictionary = ui.catalog.templates.brace.duplicate(true)
	# Start a tree from a brand-new base card without touching the catalog.
	_tree_line(ui, "start.name", "Quick Ward")
	await _click(_tree_control(ui, "start.create")); await _frames()
	_expect(ui.draft.nodes.size() == 1 and ui.draft.nodes[0].card.id == "quick_ward" and ui.draft.nodes[0].card.name == "Quick Ward", "new base card created in the tree")
	_expect(ui.draft.id == "quick_ward_paths" and ui.draft.name == "Quick Ward paths", "tree identity derived from the new base")
	_expect(not ui.catalog.templates.has("quick_ward"), "new base is not published before the tree")
	_expect(str(ui.draft.nodes[0].card.presentation.rules_text).contains("Prevent 1"), "new base has validated rules")
	# Quick upgrade: adjust the copied card in place rather than rebuilding it.
	await _click(_tree_control(ui, "add_up")); await _frames()
	_expect(_value(ui, "forge.energy") == "5" and _value(ui, "forge.xp") == "13", "forge copies base energy and suggests +3 XP")
	await _click(_tree_control(ui, "forge.energy.dec")); await _frames()
	_expect(_tree_control(ui, "forge.changes", "tree_field").text.contains("Energy 5 → 4") and _tree_control(ui, "forge.name", "tree_field").text == "Quick Ward · Swift", "forge shows change and suggests a name")
	await _click(_tree_control(ui, "forge.step.0.amount.inc")); await _frames()
	await _click(_tree_control(ui, "forge.add.draw")); await _frames()
	_expect(_tree_control(ui, "forge.changes", "tree_field").text.contains("Draw 1 card"), "compatible effect added")
	await _click(_tree_control(ui, "forge.commit")); await _frames()
	var up: Dictionary = ui._node("node_1")
	_expect(ui.draft.nodes.size() == 2 and ui.draft.edges.size() == 1 and ui._selected == "node_1", "forge creates and selects the upgrade")
	_expect(int(up.card.cost.energy) == 4 and int(up.card.program.steps[0].params.amount) == 2 and up.card.program.steps.size() == 2 and int(up.card.economy.buy) == 13, "upgrade keeps exactly the chosen adjustments")
	_expect(up.card.id == "quick_ward_paths_variant_node_1" and float(up.y) < 0.0, "upgrade placed above with a tree variant ID")
	await _canvas_click(ui, "base")
	await _click(_tree_control(ui, "add_down")); await _frames()
	await _click(_tree_control(ui, "forge.energy.inc")); await _frames()
	await _click(_tree_control(ui, "forge.commit")); await _frames()
	_expect(ui.draft.nodes.size() == 3 and float(ui._node("node_2").y) > 0.0 and int(ui._node("node_2").card.economy.buy) == 8, "cheaper variant placed below with -2 XP")
	await _key(KEY_Z, true); _expect(ui.draft.nodes.size() == 2, "undo removes the variant")
	await _key(KEY_Z, true, true); _expect(ui.draft.nodes.size() == 3, "redo restores the variant")
	# Drag the ring knob onto another card to connect it; loops and links into the base are refused.
	var source = _tree_control(ui, "node_2", "tree_node"); var target = _tree_control(ui, "node_1", "tree_node")
	await _drag(source.get_global_transform() * source.knob_center(), target.get_global_rect().get_center())
	_expect(ui.draft.edges.any(func(e): return e.from == "node_2" and e.to == "node_1"), "knob drag connects cards")
	ui._connect_cards("node_1", "node_2"); _expect(ui._message.text.contains("loop"), "loop refused")
	ui._connect_cards("node_1", "base"); _expect(ui._message.text.contains("base"), "link into base refused")
	await _canvas_click(ui, "node_2"); await _key(KEY_DELETE)
	_expect(ui._node("node_2").is_empty(), "Delete removes the selected card")
	await _key(KEY_Z, true); _expect(not ui._node("node_2").is_empty() and ui.draft.edges.size() == 3, "undo restores card and connections")
	ui._context_menu("node", "base", Vector2(400, 400)); await _frames()
	_expect(ui._menu.visible and ui._menu.get_item_text(0) == "Upgrade ↑", "right-click card menu")
	ui._menu.hide()
	await _click(_tree_control(ui, "arrange")); await _frames()
	_expect(ui._node("base").x == 0.0 and ui._node("base").y == 0.0 and ui._node("node_1").y < 0.0 and ui._node("node_2").y > 0.0, "auto-arrange keeps XP direction")
	await create_timer(0.9).timeout; await _frames()
	_expect(ui._validity.text.begins_with("✓") and not ui._publish.disabled, "live validation enables publishing: " + ui._validity.text)
	await _click(ui._publish); await _frames()
	_expect(ui._message.text.begins_with("Published") and ui.catalog.templates.has("quick_ward"), "tree with new base publishes: " + ui._message.text)
	_expect(ui.catalog.templates.brace == brace_before, "publishing a new base leaves Brace unchanged")
	var node_control := _tree_control(ui, "node_1", "tree_node")
	await _drag(node_control.get_global_rect().get_center(), node_control.get_global_rect().get_center() + Vector2(-40, 0))
	await _click(_tree_control(ui, "new")); await _frames()
	_expect(ui._confirm.visible, "new tree protects draft")
	await _click(_tree_control(ui, "discard")); await _frames()
	await _click(_tree_control(ui, "example")); await _frames()
	_expect(ui.draft.nodes.size() == 5 and ui.draft.edges.size() == 5, "example offers upgrade, cheaper, and combined paths")
	_expect(ui.draft.id == "steady_guard_paths" and ui._node("base").card.id == "steady_guard" and ui._node("base").card.name == "Steady Guard", "example uses its own new base card")
	_expect(not ui.draft.nodes.any(func(n): return n.card.id == "brace"), "example does not edit Brace")
	# A converging card lists the full change, including XP, from every route into it.
	await _canvas_click(ui, "node_3")
	var from_deeper: String = _tree_control(ui, "preview.changes.node_1", "tree_field").text
	var from_original: String = _tree_control(ui, "preview.changes.node_2", "tree_field").text
	_expect(from_deeper.contains("Saved cards") and from_deeper.contains("XP value: 13 → 17 (+4 XP)") and not from_deeper.contains("Prevent"), "converging card shows the change from its first route: %s" % from_deeper)
	_expect(from_original.contains("1 → 2") and from_original.contains("XP value: 14 → 17 (+3 XP)") and not from_original.contains("Saved cards"), "converging card shows the change from its second route: %s" % from_original)
	_expect(str(ui._canvas.summaries.node_3) == "Joins 2 paths" and str(ui._canvas.tooltips.node_3).contains("+4 XP") and str(ui._canvas.tooltips.node_3).contains("+3 XP"), "medallion and tooltip describe both routes")
	# Name plates reserve a line for every wrapped name line, so XP never overlaps the name.
	var probe = ui._canvas._nodes.node_3
	var probe_title: String = probe.title
	probe.title = "Guard"; probe.refresh()
	var one_line: float = probe.size.y
	for name in ["Strong Swing · Finisher", "Strong Swing · Decisive", "Steady Guard · Deeper guard and original piles"]:
		probe.title = name; probe.refresh()
		_expect(probe._name.get_line_count() >= 2 and probe._name_lines == 2 and probe.size.y > one_line, "long name wraps inside its plate: " + name)
	probe.title = probe_title; probe.refresh()
	# Quick edit on the converging card compares against both routes too.
	await _click(_tree_control(ui, "quick_edit")); await _frames()
	var forge_changes: String = _tree_control(ui, "forge.changes", "tree_field").get_parsed_text()
	_expect(forge_changes.contains("From Steady Guard · Deeper guard") and forge_changes.contains("From Steady Guard · Original piles") and forge_changes.contains("(+4 XP)") and forge_changes.contains("(+3 XP)"), "quick edit lists the change from every route: %s" % forge_changes)
	await _click(_tree_control(ui, "forge.xp.inc")); await _frames()
	forge_changes = _tree_control(ui, "forge.changes", "tree_field").get_parsed_text()
	_expect(forge_changes.contains("13 → 18 (+5 XP)") and forge_changes.contains("14 → 18 (+4 XP)"), "quick edit XP change updates every route")
	await _click(_tree_control(ui, "forge.cancel")); await _frames()
	_expect(int(ui._node("node_3").card.economy.buy) == 17, "cancelled quick edit leaves the card unchanged")
	await _canvas_click(ui, "base")
	node_control = _tree_control(ui, "node_1", "tree_node")
	var old_x: float = ui._node("node_1").x
	await _drag(node_control.get_global_rect().get_center(), node_control.get_global_rect().get_center() + Vector2(-30, 0))
	_expect(ui._node("node_1").x < old_x - 10, "admin node drag changes saved layout")
	await _canvas_click(ui, "node_1")
	_expect(ui._selected == "node_1", "canvas selects branch by pointer")
	await _canvas_click(ui, "base")
	# Card editor is reused without exposing standalone publishing or ID changes.
	await _click(_tree_control(ui, "edit_card")); await _frames()
	var editor = ui.get_children().filter(func(c): return c.get_script() == ui.CARD_EDITOR)[0]
	_expect(not _node(editor, "id").editable and editor._tabs.is_tab_disabled(2), "embedded editor protects tree IDs and connections")
	_node(editor, "energy").value = 1; editor._validate()
	await _click(editor._publish_button); await _frames()
	_expect(ui._node("base").card.program.steps[0].params.amount == 1, "base edit retains configured prevention")
	# Attach a visible forbidden-card requirement on the first branch.
	await _canvas_click(ui, "edge_1", true)
	_expect(ui._edge == "edge_1", "connection gate selects by pointer")
	_choose(_tree_control(ui, "rule.card", "tree_field"), "strong_swing")
	await _click(_tree_control(ui, "rule.forbid")); await _frames()
	_expect(ui.draft.edges[0].requirements[0].maximum == 0, "forbidden deck card configured with controls")
	_choose(_tree_control(ui, "rule.card", "tree_field"), "brace_plus")
	await _click(_tree_control(ui, "rule.require")); await _frames()
	_expect(ui.draft.edges[0].requirements.size() == 2, "required equipment/card configured")
	await _click(_tree_control(ui, "validate")); await _frames()
	_expect(not ui._publish.disabled, "tree validates: " + ui._message.text)
	await _click(ui._publish); await _frames()
	_expect(ui._message.text.begins_with("Published"), "tree publishes from admin: " + ui._message.text)
	if DisplayServer.get_name() != "headless":
		ui._canvas.home(); await _frames(); RenderingServer.force_draw()
		DirAccess.make_dir_recursive_absolute("res://.godot/layout-review")
		root.get_texture().get_image().save_png("res://.godot/layout-review/card-tree-admin.png")
	await _click(_tree_control(ui, "back")); await _frames()
	screen._tabs.current_tab = 5; await _frames(); ui = screen.get_node("CardTreeWorkspace")
	_expect(not ui._admin(), "player tree has no admin editing capability")
	_choose(ui._tree_pick, "steady_guard_paths"); await _frames()
	_expect(ui.draft.id == "steady_guard_paths", "choosing a tree opens it")
	_expect(not ui.state.offers.steady_guard_paths.edge_1.available, "an unowned base cannot be upgraded")
	var xp: int = int(ui.state.progression.xp)
	await _click(_tree_control(ui, "buy_collection.steady_guard")); await _frames()
	_expect(int(ui.state.progression.xp) == xp - 10 and ui._canvas.node_states.get("base") == "owned" and ui._canvas.node_states.get("node_1") == "available", "buying the base lights the tree")
	xp = int(ui.state.progression.xp)
	_expect(ui.state.offers.steady_guard_paths.edge_1.available, "deck restrictions do not block upgrades")
	await _click(_tree_control(ui, "trade.edge_1")); await _frames()
	_expect(ui._trade_bar.visible and ui._trade_text.text.contains("stored copy"), "trade confirmation explains the source copy")
	await _click(_tree_control(ui, "trade.cancel")); await _frames()
	_expect(int(ui.state.progression.xp) == xp, "cancelled trade spends nothing")
	await _confirm_trade(ui, "edge_1")
	_expect(ui._collection_counts().get("steady_guard_paths_variant_node_1", 0) == 1 and int(ui.state.progression.xp) == xp - 3, "restricted variant upgrades into collection")
	_expect(_tree_control(ui, "equip.steady_guard_paths_variant_node_1").disabled, "forbidden deck rejects equipping, not upgrading")
	await _confirm_trade(ui, "edge_1:back")
	_expect(int(ui.state.progression.xp) == xp, "stored variant can return to base")
	await _confirm_trade(ui, "edge_5")
	_expect(int(ui.state.progression.xp) == xp + 2 and ui._collection_counts().get("steady_guard_paths_variant_node_4", 0) == 1, "cheaper path refunds 2 XP and preserves card count")
	await _confirm_trade(ui, "edge_5:back")
	_expect(int(ui.state.progression.xp) == xp, "return path costs same difference")
	await _confirm_trade(ui, "edge_2")
	_expect(int(ui.state.progression.xp) == xp - 4, "alternate original-pile branch charges 4 XP")
	await _confirm_trade(ui, "edge_4")
	_expect(int(ui.state.progression.xp) == xp - 7 and ui._collection_counts().get("steady_guard_paths_variant_node_3", 0) == 1, "combined node accessible through legal alternate route")
	await _click(_tree_control(ui, "equip.steady_guard_paths_variant_node_3")); await _frames()
	_expect(ui._counts().get("steady_guard_paths_variant_node_3", 0) == 1 and int(ui.state.progression.xp) == xp - 7, "legal variant equips without charging twice")
	root.size = Vector2i(1280, 720); await _frames(); ui._canvas.home(); await _frames()
	_expect(root.get_visible_rect().encloses(_tree_control(ui, "back").get_global_rect()), "navigation remains on screen at 720p")
	if DisplayServer.get_name() != "headless":
		RenderingServer.force_draw(); root.get_texture().get_image().save_png("res://.godot/layout-review/card-tree-player-720p.png")
	var saved: Dictionary = root.get_node("LearnedBattleRuntime").card_trees("card_trees", {}, 0, "adventurer")
	_expect(saved.get("ok", false) and int(saved.result.progression.xp) == xp - 7, "tree and transactions survive reload")
	await _click(_tree_control(ui, "back")); await _frames()
	screen.inspect_entry("cards", "strong_swing"); await _frames()
	var health_before: int = screen._health()
	await _click(_control(screen, "store.strong_swing")); await _frames()
	_expect(screen._health() == health_before - 1, "standard card inspector moves card out of deck")
	await _click(_control(screen, "equip.strong_swing")); await _frames()
	_expect(screen._health() == health_before, "standard card inspector equips collected copy")
	screen.queue_free(); await process_frame
	print("CARD TREES: " + ("FAILED" if failed else "PASSED")); quit(1 if failed else 0)
