extends "res://tests/presentation/verify_card_creation_guided.gd"

# The card editor offers Before / After / Any time per segment, disables
# choices the effects cannot use, writes the mapped windows, and publishes the
# timing line in the card's rules.
func _run() -> void:
	root.size = Vector2i(1280, 720)
	var characters = SCREEN.new(); root.add_child(characters); await _frames()
	characters._tabs.current_tab = 3; await _frames()
	var ui = characters.get_node("CardCreationWorkspace")
	_pick_template(ui, "nudge"); ui._load_template(); ui._clone_template()
	ui._tabs.current_tab = 0; await _frames()
	var offense: OptionButton = _node(ui, "timing.offense")
	var defense: OptionButton = _node(ui, "timing.defense")
	_expect(offense.get_item_text(offense.selected) == "After", "die change after the first roll reads as After: " + offense.get_item_text(offense.selected))
	_expect(_option_disabled(offense, "before") and _option_disabled(offense, "any") and not _option_disabled(offense, "after"), "die effects cannot play before rolling")
	_expect(["before", "after", "any"].all(func(c): return _option_disabled(defense, c)), "offensive die effects have no Defense timing")
	var offense_reaction: CheckBox = _node(ui, "timing.offense.reaction")
	_expect(not offense_reaction.button_pressed and not offense_reaction.disabled and offense_reaction.tooltip_text.contains("pauses"), "reaction moment is an explained opt-in, off by default")
	_pick_template(ui, "brace"); ui._load_template(); ui._clone_template()
	_line_edit(ui, "id", "early_guard"); _line_edit(ui, "name", "Early Guard")
	ui._tabs.current_tab = 0; await _frames()
	offense = _node(ui, "timing.offense"); defense = _node(ui, "timing.defense")
	_expect(defense.get_item_text(defense.selected) == "Any time" and offense.get_item_text(offense.selected) == "Not playable", "prevention reads as Defense any time")
	_expect(defense.tooltip_text.contains("until you Pass"), "timing hover explains the choice: " + defense.tooltip_text)
	_choose(defense, "after"); await _frames()
	_expect(ui.draft.program.windows == ["defense_after_roll", "damage_reaction"], "After maps to the after-roll windows: " + str(ui.draft.program.windows))
	ui._validate(); await _frames()
	_expect(ui._preview.text.contains("Play: Defense, after your first defense roll."), "preview states After timing: " + ui._preview.text)
	await _click_visible(ui, _node(ui, "timing.defense.reaction")); await _frames()
	_expect("defense_reaction" in ui.draft.program.windows and ui.draft.program.windows.has("defense_after_roll"), "pointer opts into the roll review without changing After")
	ui._validate(); await _frames()
	_expect(ui._preview.text.contains("Play: Defense, after your first defense roll, or while a defense roll's result is showing."), "preview states the opt-in: " + ui._preview.text)
	await _click_visible(ui, _node(ui, "timing.defense.reaction")); await _frames()
	_expect("defense_reaction" not in ui.draft.program.windows, "opt-in clears again")
	_choose(_node(ui, "timing.defense"), "before"); await _frames()
	_expect(ui.draft.program.windows == ["defense_before_roll"], "Before maps to the before-roll window: " + str(ui.draft.program.windows))
	ui._validate(); await _frames()
	_expect(ui._preview.text.contains("Play: Defense, before your first defense roll.") and ui._status.text.contains("Defense before"), "preview and status state Before timing: " + ui._status.text)
	await _click(ui._publish_button)
	_expect(ui._error.text.begins_with("Published"), "publish before-roll card: " + ui._error.text)
	characters.queue_free(); await process_frame
	print("CARD TIMING CHOICES: " + ("FAILED" if failed else "PASSED")); quit(1 if failed else 0)
