extends RefCounted

# Concise player-facing benefits. Full targeting, timing and caps remain in rules_text.
const TEXT := {
	"accelerant": "Poison → Volatile Poison\nProvoke it · Pay 1 Catalyst",
	"agitate": "Roll every stack of one\nenemy toxin type",
	"alchemists_gamble": "1–4: Volatile Poison\n5: Miss · 6: 3 damage",
	"antidote": "Clear one negative status",
	"antivenom_draught": "Prevent 2 damage\nOptional: 1 Catalyst\nto cleanse 1 toxin",
	"battle_focus": "Draw 1 card\nGain 1 Energy",
	"bitter_reagent": "Gain 1 Catalyst",
	"coagulate": "Spend 1 enemy Poison\nPrevent 3 damage",
	"culture_flask": "Gain 2 Catalyst",
	"deep_puncture": "Trade 1 attack damage\nfor +1 Poison",
	"distill": "Poison → Volatile Poison\nSpend 1 Catalyst",
	"emergency_molt": "Prevent 2 damage\nIf blocked, gain 1 Catalyst",
	"emergency_ward": "Prevent 3 damage",
	"extract": "Spend 1 enemy Poison\nGain 2 Catalyst",
	"fever_cycle": "Provoke up to 2\nenemy toxins",
	"forked_tongue": "Change a combat die\nby +1 or −1",
	"incubate": "Apply 1 Incubation\nSpend 1 Catalyst",
	"loaded_die": "Set your die to 6",
	"measured_dose": "Gain 2 Catalyst",
	"pinprick": "Apply 1 Poison",
	"repurpose": "Spend 1 Catalyst\nDraw 2 cards",
	"sharpen_blade": "Upgrade: matching pair\napplies +1 Bleed",
	"shock_dose": "Spend 1 Volatile Poison\nDeal 3 damage",
	"slow_release": "Apply 1 Incubation",
	"spined_rebuttal": "Prevent 1 damage\nApply 1 Poison",
	"steady_hand": "Set your die to 1 or 4",
	"terminal_formula": "Terminal Bite:\n+1 DMG per Provoke\n(max +2)",
	"tip_it": "Change a die from 6 to 5",
	"twin_puncture": "Apply 2 Poison",
	"venom_lens": "Needlefang: +1 damage\nto every tier",
	"venom_reserve": "Spend 1 Catalyst\nGain 1 Energy",
	"Mock Focus": "No effect · test card",
	"Mock Guard": "No effect · test card",
	"Mock Strike": "No effect · test card"
}
